
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const OfficeAi = lazy(() => import("./pages/OfficeAi.tsx"));
const SalesAi = lazy(() => import("./pages/SalesAi.tsx"));
const TestingPage = lazy(() => import("./pages/TestingPage.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/dashboard", element: <Dashboard />},
	{ path: "/login", element: <Login />},
	{ path: "/office-ai", element: <OfficeAi />},
	{ path: "/officeai", element: <OfficeAi />},
	{ path: "/sales-ai", element: <SalesAi />},
	{ path: "/salesai", element: <SalesAi />},
	{ path: "/testing-page", element: <TestingPage />},
	{ path: "/testingpage", element: <TestingPage />},

];
